---
- name: Prepare to Join
  ansible.builtin.include_tasks: prepare.yaml
  when: inventory_hostname == groups['vms_masters'][0]
  run_once: true

- name: Join worker nodes
  ansible.builtin.include_tasks: join.yaml
  when: inventory_hostname in groups['vms_workers']
