---
# 1-st control node
- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: End play
  ansible.builtin.meta: end_play
  when: kubeadm_ca.stat.exists

- name: Create /etc/kubernetes directory
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    mode: '0700'

- name: Set kube middle version
  ansible.builtin.set_fact:
    k8s_middle_version: "{{ kube_version[2:4] | int }}"

- name: Copy kubeadm-config.yaml < 1.34
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0600'
  when: k8s_middle_version < 31

- name: Copy kubeadm-config.yaml >= 1.31
  ansible.builtin.template:
    src: kubeadm-config.v4.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0600'
  when: k8s_middle_version >= 31

- name: Load k8s containers
  ansible.builtin.command: kubeadm config images pull

- name: Calico
  when: cni == 'calico'
  block:

  - name: Install Calico
    when: enableBPF is not defined
    ansible.builtin.include_tasks: calico.yaml

  - name: Install Calico with BPF
    when: enableBPF is defined
    ansible.builtin.include_tasks: calico-bpf.yaml

- name: Setup DNS
  ansible.builtin.include_tasks: dns.yaml

- name: Kubelet enable
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
