apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway
  namespace: envoy-gateway-system
spec:
  secretName: gateway-tls
  duration: 9125h # 1y
  renewBefore: 360h # 15d
  subject:
    organizations:
      - home dev lab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.home.arpa"
    - home.arpa
  ipAddresses:
    - 192.168.125.86
    - 192.168.125.87
    - 192.168.125.88
    - 192.168.125.89
    - 192.168.125.90
  issuerRef:
    name: dev-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
