---
- name: Check if containerd config exists
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: containerd_config

- name: End play
  ansible.builtin.meta: end_play
  when: containerd_config.stat.exists

- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    suites: ["{{ ansible_facts['lsb']['codename'] | lower }}"]
    components: [stable]
    state: present
    enabled: true

- name: Install containerD from apt
  ansible.builtin.apt:
    pkg:
      - containerd.io
    update_cache: true
    state: present

- name: Check current containerd config version
  ansible.builtin.shell:
    cmd: grep -E '^version\s*=' /etc/containerd/config.toml 2>/dev/null || echo "version = 0"
  register: current_version
  changed_when: false

- name: Configure containerD from default
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
      grep version /etc/containerd/config.toml
    executable: /bin/bash
  register: config_rez
  changed_when: "current_version.stdout not in config_rez.stdout"


# - name: Add cgroup v2 [config.toml]
#   ansible.builtin.shell:
#     cmd: |
#       set -o pipefail
#       sudo sed -i 's|SystemdCgroup = false|SystemdCgroup = true|' /etc/containerd/config.toml >/dev/null
#       grep 'SystemdCgroup = true' /etc/containerd/config.toml | cut -d '=' -f2
#     executable: /bin/bash
#   register: cgroup_rez
#   changed_when: cgroup_rez == " true"

- name: Enable SystemdCgroup in containerd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*=\s*false'
    line: '            SystemdCgroup = true'
    state: present
    backrefs: yes

- name: Enable and start Containerd service
  when: "current_version.stdout not in config_rez.stdout"
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: yes
