---
- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    suites: ["{{ ansible_facts['lsb']['codename'] | lower }}"]
    components: [stable]
    state: present
    enabled: true

- name: Install containerD from apt
  ansible.builtin.apt:
    pkg:
      - containerd.io
    update_cache: true
    state: present

- name: Check current containerd config version
  ansible.builtin.shell:
    cmd: grep -E '^version\s*=' /etc/containerd/config.toml 2>/dev/null || echo "version = 0"
  register: current_version
  changed_when: false

- name: Configure containerD from default
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      sudo containerd config default | sudo tee /etc/containerd/config.toml > /deb/null
      grep version /etc/containerd/config.toml
    executable: /bin/bash
  register: config_rez
  changed_when: "current_version.stdout not in config_rez.stdout"

- name: Check current SystemdCgroup value
  ansible.builtin.shell:
    cmd: |
      grep 'SystemdCgroup = true' /etc/containerd/config.toml | cut -d '=' -f2 \
      || echo "false"
  register: current_cgroups_value
  changed_when: false

# - name: Add cgroup v2 [config.toml]
#   ansible.builtin.shell:
#     cmd: |
#       set -o pipefail
#       sudo sed -i 's|SystemdCgroup = false|SystemdCgroup = true|' /etc/containerd/config.toml
#       grep 'SystemdCgroup = true' /etc/containerd/config.toml | cut -d '=' -f2
#     executable: /bin/bash
#   register: cgroup_rez
#   changed_when: cgroup_rez | trim == current_cgroups_value | trim
#
- name: Enable SystemdCgroup in containerd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*=\s*false'
    line: '            SystemdCgroup = true'
    backrefs: yes
  register: containerd_config

# - name: Show 'cgroup_rez'
#   debug:
#     msg: "The result in 'containerd_config_changed': {{ containerd_config_changed }}"

- name: Check if containerd config exists
  ansible.builtin.stat:
    path: /etc/containerd/config.toml

- name: Enable and start Containerd service
  when: containerd_config.changed
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: yes
